version: '3.8'

services:
  # 1. Cơ sở dữ liệu MySQL
  mysql:
    image: mysql:8.0
    container_name: race_condition_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: race_condition_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Cache Redis (Xử lý Race Condition)
  redis:
    image: redis:alpine
    container_name: race_condition_redis
    restart: always
    ports:
      - '6379:6379'

  # 3. Message Broker Kafka (Bản chuẩn Apache, dùng KRaft, KHÔNG Zookeeper)
  kafka:
    image: apache/kafka:latest
    container_name: race_condition_kafka
    restart: always
    ports:
      - '9092:9092'
    environment:
      # Cấu hình KRaft (Tự quản lý cluster)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Cấu hình port và mạng giao tiếp
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # Trỏ đúng tên service 'kafka' để NestJS gọi được
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # Cấu hình cho môi trường Dev (1 Node duy nhất)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # 4. Backend NestJS của bạn
  server:
    build:
      context: .
      dockerfile: .DockerFile
    container_name: race_condition_server
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npx prisma generate && rm -rf dist *.tsbuildinfo && npm run start:dev"
    depends_on:
      - mysql
      - redis
      - kafka
    # Chỉ cần load file .env là đủ, không cần map lại từng biến thủ công
    env_file:
      - .env

  #5. Kafka UI (Giao diện trực quan để xem Topic & Message)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: race_condition_kafka_ui
    restart: always
    ports:
      - '8080:8080' # Bạn sẽ truy cập qua http://localhost:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local-Kafka-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 # Trỏ kết nối vào container kafka
    depends_on:
      - kafka

  # 6. Redis Insight (Giao diện trực quan quản lý Redis)
  redisinsight:
    image: redis/redisinsight:latest
    container_name: race_condition_redisinsight
    restart: always
    ports:
      - '5540:5540' # Bạn sẽ truy cập qua http://localhost:5540
    depends_on:
      - redis

volumes:
  mysql_data:
  server_node_modules:
